name: Deploy VuePress site to Server

on:
  push:
    branches:
      - main  # 或者你的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build VuePress site
        run: npm run build
        
      - name: Debug file structure
        run: |
          echo "Current directory:"
          pwd
          echo "\nList current directory:"
          ls -la
          echo "\nList src directory:"
          ls -la src
          echo "\nList .vuepress directory:"
          ls -la src/.vuepress
          echo "\nList dist directory:"
          ls -la src/.vuepress/dist
          
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "src/.vuepress/dist"
          target: "/home/lighthouse/odyssey"
          strip_components: 2
          overwrite: true